spring:
  application:
    name: telepass
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false # Mail configuration for OTP - Google SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: daraa.dev@gmail.com
    password: kybx juvu gcui tdrs # Make sure to use App Password if 2FA is enabled on Gmail
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
            trust: smtp.gmail.com
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
          localhost: telepass-app # Explicitly set hostname to avoid invalid characters
        debug: false

  # Disable actuator endpoints that cause excessive logging
  management:
    endpoints:
      enabled-by-default: false
    health:
      mail:
        enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
      file-size-threshold: 2KB

# Logging configuration to reduce verbosity
logging:
  level:
    org.hibernate: WARN
    org.springframework: WARN
    org.apache: WARN
    com.zaxxer.hikari: WARN
    jakarta.mail: DEBUG
    org.springframework.boot.actuate: ERROR
    org.telegram.telegrambots: WARN
    com.example.tb.configuration.TelegramBotSessionManager: INFO
    com.example.tb.authentication.service.admin.AdminServiceImpl: INFO
    com.example.tb.jwt: INFO # Reduce JWT-related logging noise
    root: INFO

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  refresh-token: 604800

file:
  uploadPath: C:\Users\Techo\OneDrive\Documents\Internship\YEAR5\telepass_backend\src\main\resources\files

file-upload:
  server-path: /home/was/bizweb_api/files

WebBaseUrl: http://localhost:3000/
BaseUrl: http://localhost:8080/

server:
  port: 8080

myAdmin:
  username: admin
  password: admin123

# OTP Configuration
otp:
  expiration-time: 300 # 5 minutes in seconds
  length: 6 # Number of digits in OTP
  max-attempts: 3 # Maximum verification attempts
  cooldown-time: 60 # Cooldown time in seconds before requesting new OTP
  email:
    subject: "Your OTP Code"
    template: |
      Dear User,
        Your One-Time Password (OTP) is: {otp}

      This code will expire in {expiration} minutes.

      If you didn't request this code, please ignore this email.

      Best regards,
      Telepass Team

# Disable debug mode for email testing (set to false for production)
mail:
  debug:
    mode: false
