spring:
  application:
    name: telepass
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  # Disable mail configuration to prevent health check failures
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  # Add minimal mail configuration to prevent property errors
  mail:
    username: noop@localhost
  # Disable actuator endpoints that cause excessive logging
  management:
    endpoints:
      enabled-by-default: false
    health:
      mail:
        enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
      file-size-threshold: 2KB

# Logging configuration to reduce verbosity
logging:
  level:
    org.hibernate: WARN
    org.springframework: WARN
    org.apache: WARN
    com.zaxxer.hikari: WARN
    jakarta.mail: ERROR
    org.springframework.boot.actuate: ERROR
    org.telegram.telegrambots: WARN
    com.example.tb.configuration.TelegramBotSessionManager: INFO
    com.example.tb.authentication.service.admin.AdminServiceImpl: INFO
    com.example.tb.jwt: INFO # Reduce JWT-related logging noise
    root: INFO

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  refresh-token: 604800

file:
  uploadPath: C:\Users\Techo\OneDrive\Documents\Internship\YEAR5\telepass_backend\src\main\resources\files

file-upload:
  server-path: /home/was/bizweb_api/files

WebBaseUrl: http://localhost:3000/
BaseUrl: http://localhost:8080/

server:
  port: 8080

myAdmin:
  username: admin
  password: admin123
