spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: gosellingproject@gmail.com
    password: mmlrtnqtokjctfgx
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: contact@email.com
      from:
        name: B2B
  application:
    name: telepass
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
      file-size-threshold: 2KB

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  refresh-token: 604800
file:
  uploadPath: C:\Users\Techo\OneDrive\Documents\Internship\YEAR5\telepass_backend\src\main\resources\files
file-upload:
  server-path: /home/was/bizweb_api/files
  client-path: /files/**
  base-uri: http://localhost:8080
myAdmin:
  username: Admin
  password: Telepass1@
BaseUrl: http://localhost:8080/
WebBaseUrl: http://localhost:3000/
google:
  client-id: your-client-id
